### ISSUE TITLE
Updater api still erroring with null

### ISSUE THREAD

**Issue by Rochet2** [UniversityOfHelsinkiCS/oodikone#1139]
Hmm, wasnt this fixed?
Seems that an error prevented updating of the container with latest version.

```
updater_scheduler    | {"task":"013317670","status":"DONE","student":true,"level":"info","message":"Status changed for 013317670 to DONE"}
updater_api_3        | (node:24) UnhandledPromiseRejectionWarning: Error: API returned null for studentnumber 015081357.
updater_api_3        |     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:91:11)
updater_api_3        |     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_3        | (node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
updater_scheduler    | {"task":"014614534","status":"FETCHED","student":true,"level":"info","message":"Status changed for 014614534 to FETCHED"}
```

**Comment by woltsu** [comment]
what in tarnation
