### ISSUE TITLE
Errors in updater_api

### ISSUE THREAD

**Issue by Rochet2** [UniversityOfHelsinkiCS/oodikone#1547]
```
tkt_oodi@svm-77:~/oodikone_updater$ docker-compose logs --tail=20000 --timestamp updater_api | grep "2019-09-22T00:56\|2019-09-23T19:27\|2019-09-23T19:21\|2019-09-23T19:27\|2019-09-22T00:25\|2019-09-22T01:24\|2019-09-22T00:52\|2019-09-2
2T01:24\|2019-09-23T18:56\|2019-09-25T18:59\|2019-09-25T19:25\|2019-09-28T23:24\|2019-09-29T00:59\|2019-09-29T00:54\|2019-09-29T01:23\|2019-09-29T01:27\|2019-09-29T01:21\|2019-10-01T18:26\|2019-10-01T18:56\|2019-10-01T18:56\|2019-10-01T
17:58\|2019-10-01T18:28\|2019-10-01T18:58\|2019-10-02T18:57\|2019-10-02T18:55"
updater_api_8        | 2019-09-28T23:24:34.811116496Z TypeError: api.studyattainments is not iterable
updater_api_8        | 2019-09-28T23:24:34.837519635Z     at formatStudyattainments (/usr/src/app/doo_api_database_updater/updater_formatter.js:60:24)
updater_api_8        | 2019-09-28T23:24:34.837553130Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:93:5)
updater_api_8        | 2019-09-28T23:24:34.837578454Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_9        | 2019-09-29T00:59:03.954447986Z TypeError: api.studyattainments is not iterable
updater_api_9        | 2019-09-29T00:59:03.968485653Z     at formatStudyattainments (/usr/src/app/doo_api_database_updater/updater_formatter.js:60:24)
updater_api_9        | 2019-09-29T00:59:03.968510873Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:93:5)
updater_api_9        | 2019-09-29T00:59:03.968517854Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_8        | 2019-09-29T00:54:38.396008565Z TypeError: Cannot read property 'map' of undefined
updater_api_8        | 2019-09-29T00:54:38.418024643Z     at formatCourseEnrollments (/usr/src/app/doo_api_database_updater/updater_formatter.js:39:111)
updater_api_8        | 2019-09-29T00:54:38.418055040Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:95:5)
updater_api_8        | 2019-09-29T00:54:38.418062748Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_8        | 2019-09-29T01:23:04.821238793Z TypeError: api.studyattainments is not iterable
updater_api_8        | 2019-09-29T01:23:04.836824884Z     at formatStudyattainments (/usr/src/app/doo_api_database_updater/updater_formatter.js:60:24)
updater_api_8        | 2019-09-29T01:23:04.836852426Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:93:5)
updater_api_8        | 2019-09-29T01:23:04.836859163Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_2        | 2019-09-29T01:27:18.272814787Z TypeError: Cannot read property 'map' of undefined
updater_api_2        | 2019-09-29T01:27:18.280779923Z     at formatCourseEnrollments (/usr/src/app/doo_api_database_updater/updater_formatter.js:39:111)
updater_api_2        | 2019-09-29T01:27:18.280797549Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:95:5)
updater_api_2        | 2019-09-29T01:27:18.280804690Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_10       | 2019-09-29T01:21:29.443020417Z TypeError: Cannot read property 'map' of undefined
updater_api_10       | 2019-09-29T01:21:29.455017115Z     at formatSemesterEnrollments (/usr/src/app/doo_api_database_updater/updater_formatter.js:81:115)
updater_api_10       | 2019-09-29T01:21:29.455039931Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:94:5)
updater_api_10       | 2019-09-29T01:21:29.455056380Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_4        | 2019-10-01T18:26:05.691235823Z TypeError: api.studyattainments is not iterable
updater_api_4        | 2019-10-01T18:26:05.771512425Z     at formatStudyattainments (/usr/src/app/doo_api_database_updater/updater_formatter.js:60:24)
updater_api_4        | 2019-10-01T18:26:05.771584481Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:93:5)
updater_api_4        | 2019-10-01T18:26:05.771601637Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_8        | 2019-10-01T18:56:48.407838950Z TypeError: Cannot read property 'map' of undefined
updater_api_8        | 2019-10-01T18:56:48.429572464Z     at formatCourseEnrollments (/usr/src/app/doo_api_database_updater/updater_formatter.js:39:111)
updater_api_8        | 2019-10-01T18:56:48.429600754Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:95:5)
updater_api_8        | 2019-10-01T18:56:48.429608334Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_3        | 2019-10-01T18:56:31.865905265Z TypeError: api.studyattainments is not iterable
updater_api_3        | 2019-10-01T18:56:31.885141295Z     at formatStudyattainments (/usr/src/app/doo_api_database_updater/updater_formatter.js:60:24)
updater_api_3        | 2019-10-01T18:56:31.885180212Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:93:5)
updater_api_3        | 2019-10-01T18:56:31.885193727Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_1        | 2019-10-01T17:58:44.893102919Z TypeError: Cannot read property 'map' of undefined
updater_api_1        | 2019-10-01T17:58:44.898665606Z     at formatCourseEnrollments (/usr/src/app/doo_api_database_updater/updater_formatter.js:39:111)
updater_api_1        | 2019-10-01T17:58:44.898687487Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:95:5)
updater_api_1        | 2019-10-01T17:58:44.898696110Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_1        | 2019-10-01T18:28:15.457388755Z TypeError: api.studyattainments is not iterable
updater_api_1        | 2019-10-01T18:28:15.457581188Z     at formatStudyattainments (/usr/src/app/doo_api_database_updater/updater_formatter.js:60:24)
updater_api_1        | 2019-10-01T18:28:15.457600311Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:93:5)
updater_api_1        | 2019-10-01T18:28:15.457609056Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_1        | 2019-10-01T18:58:59.833823770Z TypeError: Cannot read property 'map' of undefined
updater_api_1        | 2019-10-01T18:58:59.835570944Z     at formatCourseEnrollments (/usr/src/app/doo_api_database_updater/updater_formatter.js:39:111)
updater_api_1        | 2019-10-01T18:58:59.835588474Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:95:5)
updater_api_1        | 2019-10-01T18:58:59.835596668Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_10       | 2019-10-02T18:57:02.925108164Z TypeError: Cannot read property 'map' of undefined
updater_api_10       | 2019-10-02T18:57:02.942955548Z     at universityEnrollmentDateFromStudyRights (/usr/src/app/doo_api_database_updater/oodi_data_mapper.js:24:35)
updater_api_10       | 2019-10-02T18:57:02.943039307Z     at Object.getStudentFromData (/usr/src/app/doo_api_database_updater/oodi_data_mapper.js:61:33)
updater_api_10       | 2019-10-02T18:57:02.943064424Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:90:36)
updater_api_10       | 2019-10-02T18:57:02.943079654Z     at process._tickCallback (internal/process/next_tick.js:68:7)
updater_api_1        | 2019-10-02T18:55:08.766596851Z TypeError: api.studyattainments is not iterable
updater_api_1        | 2019-10-02T18:55:08.800663755Z     at formatStudyattainments (/usr/src/app/doo_api_database_updater/updater_formatter.js:60:24)
updater_api_1        | 2019-10-02T18:55:08.800709419Z     at getStudent (/usr/src/app/doo_api_database_updater/updater_formatter.js:93:5)
updater_api_1        | 2019-10-02T18:55:08.800717859Z     at process._tickCallback (internal/process/next_tick.js:68:7)
tkt_oodi@svm-77:~/oodikone_updater$
```

**Comment by woltsu** [comment]
For some endpoints oodi seems to randomly return a status 200 response with a body like this:
```
{ status: 500,
 exception:
 { message 'SQL STUFF....' } }
```

**Comment by woltsu** [comment]
New error: `null value in column "id" violates not-null constraint`

**Comment by woltsu** [comment]
More sql errors... f.ex. from student 013113285
