### ISSUE TITLE
Populations search explodes backend after clicking on Study programme overview with only one year

### ISSUE THREAD

**Issue by cxcorp** [UniversityOfHelsinkiCS/oodikone#1640]

**Comment by cxcorp** [comment]
example with anon data: `/study-programme/KH50_005`:

1. Click on Total's arrow
  > ![image](https://user-images.githubusercontent.com/21111572/67486321-833d9080-f674-11e9-84c8-f362de7a483d.png)
2. Notice path ends with `/populations?.......&years=2017`
3. Explode backend
```
backend              | TypeError: req.query.years.map is not a function
backend              |     at router.get (/usr/src/app/src/routes/population.js:243:25)
backend              |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
```
